import Image from "next/image";
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title> PLatzi </title>
        <meta name="description" content="Generated by platzi" />
        <link rel="stylesheet" href="favicon.ico"/>
      </Head>

    
      <main>
      <h1 className="text-3xl font-bold underline">Hey Platzi 😎!</h1>
      </main>
    
    </div>
    
  );
}
